### ISSUE TITLE
Tomorrow's presentation

### ISSUE THREAD

**Issue by yihui** [uncoast-unconf/rolldown#7]
I want to brainstorm ideas about tomorrow afternoon's presentation. I have one idea: turn this thread https://github.com/uncoast-unconf/uu-2019-day-zero/issues/11 to a storytelling (R Markdown) document and demo it in our talk. Wouldn't it be a perfect application of **rolldown**?!!

**Comment by iqis** [comment]
I got this figured out to the present stage . If I try to add the entirety of all the texts, step activation will not work on any section. 

```

---
title: "Hi from Uncoast Unconf 2019"
output:
  rolldown::scrollama: 
    number_sections: no
    self_contained: no
---

  ```{css, echo=FALSE}
.level1 {
  min-height: 400px;
  border: 1px solid;
  margin-bottom: 4em;
  padding: 1em 2em 2em;
}
.is-active {
  background-color: yellow;
}
```
# ijlyttle
![](https://avatars0.githubusercontent.com/u/2800934?s=88&v=4)
<p>I think this will be a great way to make sure we feel good about our GitHub accounts.</p>
<p>Please respond to this issue by introducing yourself, or if you like you can respond with an emoji.</p>


# AmeliaMN
![](https://avatars0.githubusercontent.com/u/2576787?s=88&v=4)
<p>Hello! I'm Amelia McNamara, I live in Minneapolis and teach at the University of St Thomas.</p>
<p>Not sure if Ian is going to cover this later, but I think it's fun to have a picture (either of yourself, or something else you like) as your Github profile picture, rather than the default picture Github picks for you. If you want to do that, go up to the top right corner of this screen and click the drop-down arrow next to your current picture and select "Your Profile." Once you're there, just click on the square of your current picture and upload a new one!</p>
<p><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/2576787/54565708-f70c1200-499c-11e9-9ce8-0bfca408e603.png"><img width="1818" alt="Screen Shot 2019-03-18 at 4 37 35 PM" src="https://user-images.githubusercontent.com/2576787/54565708-f70c1200-499c-11e9-9ce8-0bfca408e603.png" style="max-width:100%;"></a></p>
<p>I'm excited for the unconf!<br><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/2576787/54565587-b1e7e000-499c-11e9-9fca-1cfd19811b13.gif"><img src="https://user-images.githubusercontent.com/2576787/54565587-b1e7e000-499c-11e9-9fca-1cfd19811b13.gif" alt="excited2" style="max-width:100%;"></a></p>


# ijlyttle
![](https://avatars0.githubusercontent.com/u/2800934?s=88&v=4)
<p>Thanks Amelia!</p>
<p>I'm so glad to be working with <a class="user-mention" data-hovercard-type="user" data-hovercard-url="/hovercards?user_id=2576787" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://github.com/AmeliaMN">@AmeliaMN</a>, <a class="user-mention" data-hovercard-type="user" data-hovercard-url="/hovercards?user_id=9620552" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://github.com/haleyjeppson">@haleyjeppson</a>, and <a class="user-mention" data-hovercard-type="user" data-hovercard-url="/hovercards?user_id=6137322" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://github.com/sctyner">@sctyner</a> on this day-zero, not least because I am forgetting to go over a lot of stuff, but together, we'll be covered!</p>
<p>Also, you can use GitHub handles (mine is <a class="user-mention" data-hovercard-type="user" data-hovercard-url="/hovercards?user_id=2800934" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://github.com/ijlyttle">@ijlyttle</a>) to tag people into a conversation.</p>
<p>Where are my manners? I'm Ian Lyttle, I work as a data-scientist at Schneider Electric in Cedar Rapids, IA. I've used R for about eight years, and while I am a fan of the tidyverse, I am a bigger fan of the community!</p>
<p>I, too, am excited for the unconf!</p>
<p><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/2800934/54568132-15c1d700-49a4-11e9-9836-a77cc0266471.gif"><img src="https://user-images.githubusercontent.com/2800934/54568132-15c1d700-49a4-11e9-9836-a77cc0266471.gif" alt="giphy" style="max-width:100%;"></a></p>


# mkosmicki
![](https://avatars1.githubusercontent.com/u/35268474?s=88&v=4)
<p>I've got my RStudio updated and popped in here to say "Hello World".  (The first thing you ever do when programming....right?  LOL) I'm really excited to meet all of you in a few weeks at the unconf. I'm hoping to learn a lot from those who have been using R for a lot longer than I have.</p>
<p>I have a BA in Clinical Psych and a MA in Ed Psych (Quantitative &amp; Qualitative Methods) from the University of Nebraska - Lincoln (Go Huskers!). I spent 16 years in state government (14 working for Nebraska's PBS &amp; NPR station) before moving to Iowa.</p>
<p>I currently work for an advertising agency in West Des Moines as a Sr. Marketing Analyst. I managed to go a very long time using SPSS (like 25 years!) for most of my analysis needs. Now the time has come to get busy with R.</p>
<p><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/35268474/54635133-896ded80-4a51-11e9-9a0a-7c4def1bbeef.jpg"><img src="https://user-images.githubusercontent.com/35268474/54635133-896ded80-4a51-11e9-9a0a-7c4def1bbeef.jpg" alt="Bitstrip_Rosie" style="max-width:100%;"></a></p>
<p>Also....I was wondering if anyone had played with RStudio Cloud? I was installing RStudio on my home laptop last night and saw RStudio Cloud Alpha.</p>



```{r echo = FALSE}
rolldown::scrollama_setup(options = list(step = ".section.level1", offset = 0.35))
```

```
